### ISSUE TITLE
Add windowing

### ISSUE THREAD

**Issue by klangner** [klangner/dsp#5]
Hamming

**Comment by garro95** [comment]
I started the implementation of some filters. You can see at https://github.com/garro95/dsp/tree/windows
I would appreciate some feedback on the API

**Comment by klangner** [comment]
I like the idea that there are functions which creates Window structure.
But I was thinking that after we create Window we should be able to **apply** it to the signal.

So something like:
```rust
pub struct Window {
    apply: Box<Fn(Signal) -> Signal>
}
```

Then we could use it like:
```rust
let sig = Signal::new(vec![Complex::new(1., 0.), Complex::new(1., 0.), Complex::new(1., 0.)]);
let win = welch(10);
let new_signal = win.apply(sig);
```

It means that Window is not generator of samples but operation which you can apply to the signal.

What do you think?

**Comment by garro95** [comment]
I think that the generator of samples is not the way to go, also because with that architecture it is difficult to perform optimizations like exploiting SIMD instructions or implement some sort of parallelism.
I have also seen that the `vectors` module already contains the logic for operations between vectors and that could be the right place to optimize.
This means that also the `windows` module should perform the apply operation using that implementation.
Probably the best thing to do is just to compute all the samples of the window at the construction and save the resulting Vector in the Window struct. The apply operation, then, will simply perform the multiplication.

**Comment by klangner** [comment]
Ok.
What is important for me is to have good API which operates on Signal not on Vector. Especially because Signal also contains information about sample_rate which possible could be used in windowing operation. 
So maybe we can leave function **rectangle** as sample generator. But function Window::apply will:
  * Convert signal to the vector
  * Get window samples as vector
  * Multiply element wise both vectors
  * Create and return new signal

In the future I would also like to add window operation based on time not on number of samples. But maybe this will end up in another package because I like you suggestion that we can cache window points.

**Comment by klangner** [comment]
Just to be clear **Get window samples as vector** can be run during construction time.

**Comment by garro95** [comment]
So, my current implementation (see the windows branch of my fork) is OK for you?

**Comment by klangner** [comment]
Yes it looks ok.

I would only allow to apply window to signal with any size. 
It means removing:
```rust
assert_eq!(self.samples.len(), signal.len());
```

It mean that window is signal of infinite length with zero outside where there are no samples.

So instead of this assert maybe it would be better to use function **slice** if necessary.

**Comment by garro95** [comment]
I left that function as it was, but I added another one that apply the window in a specific position. In fact I think that, if the signal and the window have different sizes, choose on where to apply it would be arbitrary.

**Comment by garro95** [comment]
Now, it's only left to add some test to see if the implementation works correctly
